### ISSUE TITLE
iOS Post build script causes Unity Cloud builds to fail - mismatched bundle identifier

### ISSUE THREAD

**Issue by HzrdIRL** [OneSignal/OneSignal-Unity-SDK#111]
**Description:**
iOS builds fail when using the Unity Cloud platform. The PostProcessBuildPlayer_iOS script is adding "OneSignalNotificationServiceExtension" to the bundleID which causes builds to fail with mismatched provisioning information. See the log output below for details.

**Environment**
Unity 2018.1.0f2
OneSignal Unity SDK v2.7.0
No dependencies
Only occurs for iOS builds (development and production)

**Steps to Reproduce Issue:**
1. Add the OneSignal SDK to a Unity project
2. Push the changes to a source control repo
3. Build the project from the repo through Unity Cloud with the following configuration

![image](https://user-images.githubusercontent.com/8650984/40265870-f8e4b878-5b83-11e8-8ef8-b71030b7e1e1.png)

**Extra Information**
142:  + Building with Xcode 9.3
143: ▸ Code Signing Error: Provisioning profile "XXX" has app ID "XXX", which does not match the bundle ID "XXX.OneSignalNotificationServiceExtension".
144: ▸ Code Signing Error: Provisioning profile "XXX" doesn't match the entitlements file's value for the application-identifier entitlement.
145: ▸ Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.3'
146: fastlane finished with errors
147: /BUILD_PATH/.mason/buildpacks/xcode/bin/compile:253:in `block in build': ! xcode build failed. (RuntimeError)
148: ! build of 'ios' failed. compile failed

**Comment by HzrdIRL** [comment]
I have resolved the issue myself by removing the line that updates the bundleID. But I would prefer an official response/fix, thanks! :)

**Comment by Nightsd01** [comment]
@HzrdIRL it’s not an issue with the build script, you need to go into the Apple developer portal and provision the extension device. 

To make things easier, if you open the project in Xcode it can automatically create a provisioning profile for you. From then on the Unity cloud build should work.

**Comment by CameronGoosen** [comment]
Have you been able to resolve this issue? I'm having the same error.

**Comment by HzrdIRL** [comment]
I am working on it now. According to the people at OneSignal, you can build the project in Xcode (with auto signing set On) and it will update your provisioning profile/certificates. But you'll need to export the cert from your keychain app as a .p12 and upload to Unity Cloud. I'm updating the SDK in my Unity project, then attempting a cloud build with the updated p12/provisioning profile. I expect it to work, otherwise I'll try and re-open this ticket. 

Hopefully they release documentation to walk us through this process for cloud builds.

**Comment by CameronGoosen** [comment]
@HzrdIRL Thanks for the reply.

iOS really knows how to make things difficult, please keep me updated on any progress you make 👍 

Hoping for some documentation as well, this process isn't as simple as it seems and there is absolutely no help online.

**Comment by HzrdIRL** [comment]
If you don't have a mac with xCode you will probably have a hard time getting this to work, since I am relying on the auto-provisioning to fix up my settings with the Apple dev portal. It is possible to do all of this without a mac, but in my experience it just makes life a lot easier... :( Apple really make things painful otherwise.

**Comment by HzrdIRL** [comment]
@Nightsd01 - Can you give us some info on how cloud builds are meant to work now? Because Unity Cloud doesn't support multiple provisioning profiles, which xCode 9 now uses for extensions/embedded apps... and we can't use xCode 8 because its older than the version you've used to build the SDK (at least I get errors when trying to build in xCode until I upgraded to 9.3, then it worked again).

So this issue is still occuring, and it's unclear how we're supposed to resolve it. Thanks!

**Comment by Nightsd01** [comment]
@HzrdIRL we are contacting Unity to see how we can handle this extension provisioning issue for Unity cloud build. 

It seems pretty silly that UCB would not support something as basic as app extensions so I’m hoping they’ll let me know a workaround. 

In the mean time I would suggest uploading builds to the App Store directly from a Mac. It’s not a great solution, but it’s a better idea than removing the extension entirely

**Comment by CameronGoosen** [comment]
@Nightsd01 Thanks for the update, cloud build is such an important feature in our testing.

Will be rolling back to OneSignal 2.5.0 and just not using Action buttons.

**Comment by HzrdIRL** [comment]
@CameronGoosen I didn't think that 2.5.0 worked with UCB, how are you handling the post-build provisioning for iOS? Cheers!

**Comment by CameronGoosen** [comment]
@HzrdIRL @Nightsd01 I'll explain, we did send all of this information to josh.kasten@onesignal.intercom-mail.com in January but obviously the information must have gotten lost along the way.

We have a PostProcessor that includes CLANG_ENABLE_MODULES = YES which seems to automatically tell XCode to link in the required frameworks, including the "UserNotifications.framework". Which is what was causing the error in UCB.

`using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;

public class PostProcessor {

	// tells Xcode to automatically @include frameworks
	// credit : https://github.com/scarlet/ScarletPostProcessor

    [PostProcessBuild(1500)]
	public static void OnPostProcessBuild(BuildTarget target, string path)
	{
		#if UNITY_IPHONE
		if (target != BuildTarget.iOS)
        {
			return;
		}

		string pbxproj = path + "/Unity-iPhone.xcodeproj/project.pbxproj";

		string insertKeyword = "buildSettings = {";
		string foundKeyword = "CLANG_ENABLE_MODULES";
		string modulesFlag = "				CLANG_ENABLE_MODULES = YES;";

		List<string> lines = new List<string>();
			
		foreach (string str in File.ReadAllLines(pbxproj))
        {
			if (!str.Contains(foundKeyword))
            { 
				lines.Add(str);
			}
			if (str.Contains(insertKeyword))
            {
				lines.Add(modulesFlag);
			}
		}
	
		using (File.Create(pbxproj)) {}

		foreach (string str in lines)
        {
			File.AppendAllText(pbxproj, str + Environment.NewLine);
		}

		#endif
	}	
}`

Then we added a an EntitlementsPostProcess to set the entitlements correctly because iOS Push notifications require identity entitlements. Because the PostProcessBuild class below is an Editor class (just like the first one to amend the xcode project file) it needs to go into an Editor folder (can be a subfolder of your OneSignal Folder).

`using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using System.Collections;
using System.IO;


public class EntitlementsPostProcess : ScriptableObject
{
    public DefaultAsset m_entitlementsFile;

    [PostProcessBuild]
    public static void OnPostProcess(BuildTarget buildTarget, string buildPath)
    {
        if (buildTarget != BuildTarget.iOS)
        {
            return;
        }

        var dummy = ScriptableObject.CreateInstance<EntitlementsPostProcess>();
        var file = dummy.m_entitlementsFile;
        ScriptableObject.DestroyImmediate(dummy);
        if (file == null)
        {
            return;
        }

        var proj_path = PBXProject.GetPBXProjectPath(buildPath);
        var proj = new PBXProject();
        proj.ReadFromFile(proj_path);

        // target_name = "Unity-iPhone"
        var target_name = PBXProject.GetUnityTargetName();
        var target_guid = proj.TargetGuidByName(target_name);
        var src = AssetDatabase.GetAssetPath(file);
        var file_name = Path.GetFileName(src);
        var dst = buildPath + "/" + target_name + "/" + file_name;
        FileUtil.CopyFileOrDirectory(src, dst);
        proj.AddFile(target_name + "/" + file_name, file_name);
        proj.AddBuildProperty(target_guid, "CODE_SIGN_ENTITLEMENTS", target_name + "/" + file_name);

        proj.WriteToFile(proj_path);
    }
}`

We then create another code module called <your app name>.entitlements. We currently put this in Assets/Plugins/iOS:

`<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

  <dict>

    <key>aps-environment</key>

    <string>production</string>

  </dict>

</plist>`

Then at design time, click on the EntitlementsPostProcess file. In the top right there is an inspector slot to drag an Entitlements file. Navigate to the app.entitlements file and drag this to the Entitlements file slot. This allows us to easily customise the required entitlements inside the app.entitlements file. You could however just hardcode the apps-environment production entitlement into your EntitlementsPostProcess.

Some info from Apple:
https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingLocalAndPushNotifications.html#//apple_ref/doc/uid/TP40011195-CH3-SW1

The aps-environment production entitlement does not appear to be automatically contained within the provisioning profile so it needs to be explicitly set.

Hope this all helps!

**Comment by Nightsd01** [comment]
We did some research and it turns out Unity's cloud build service does not support extensions _at all_. Their cloud build system will not let you sign or provision extensions correctly, like the iOS notification extension service.

As a result, we have added preprocessor checks in our build script (#120) to fix this problem.

Unfortunately, the Extension Service is required for several things:
1. It will soon be required for badge increment/decrement logic. We are moving the count logic from our backend to the client to improve consistency. So unless you have an extension service you will no longer be able to send notifications that increase/decrease the badge count by some amount (you will still be able to set it directly, but you'd need to maintain the count on your own backend)

2. Without the extension service, you won't be able to send push notifications with images/buttons/attachments/etc.

3. You won't be able to use some firebase analytics that our SDK provides

Because of this, I would _heavily_ recommend moving away from unity cloud build for production builds until they resolve this silly issue.
