### ISSUE TITLE
Issue in 2.7.2 still occuring

### ISSUE THREAD

**Issue by Fyb3roptik** [OneSignal/OneSignal-Unity-SDK#116]
Issue #114 was closed, but the fix was only for iOS. My issue was with Android not compiling properly! I saw #115 but there is no newer release with this fix in it. Please make a 2.7.3 release ASAP!

**Comment by Fyb3roptik** [comment]
Also, for iOS is giving this error in Unity:

```
Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs(7,29): error CS0234: The type or namespace name `Extensions' does not exist in the namespace `UnityEditor.iOS.Xcode'. Are you missing an assembly reference?
```

**Comment by Fyb3roptik** [comment]
Getting this issue with 2.7.0 as well. Is there a reason this is happening?

**Comment by Fyb3roptik** [comment]
2.6.4 works for me. I am using Unity 5.6.5

**Comment by Nightsd01** [comment]
@Fyb3roptik this issue was fixed in a PR yesterday. 2.7.2 was released two days ago. We will be coming out with a new release soon. Git auto closes your issue when we merge the PR to master. Please don’t open duplicate tickets. The update will be released soon, in the mean time, you can continue to use 2.6.4
