### ISSUE TITLE
CommandInvokationFailure: Unable to convert classes into dex format. C:/Program Files/Java/jdk1.8.0_171\bin\java.exe -Xmx2048M -

### ISSUE THREAD

**Issue by KamranMahmood** [OneSignal/OneSignal-Unity-SDK#118]
-CommandInvokationFailure: Unable to convert classes into dex format. C:/Program Files/Java/jdk1.8.0_171\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/123/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" 

-Error building Player: 2 errors -Build completed with a result of 'Failed' UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (This errors i found any solution please)

*This error comes during build apk. Using adMob sdk and unity ads sdk ads show successfully in game but is error can't resolve i want to see my game in my device.

**Comment by Nightsd01** [comment]
We have an issue template that asks for all sorts of details you did not provide....I'll be closing this issue until you can at least provide some basic info.

For example, what version of the SDK are you using? What makes you think this issue is related to the OneSignal SDK (I don't see the word OneSignal in your error message or description)...

When you provide some info, if it is related to the onesignal SDK, I'll be happy to reopen + investigate.
