### ISSUE TITLE
DirectoryNotFoundException when building for iOS

### ISSUE THREAD

**Issue by RyuMaster** [OneSignal/OneSignal-Unity-SDK#132]
Latest Unity and 2.7.4, when building for iOS, gives:

DirectoryNotFoundException: Could not find a part of the path 

"G:\xxx\Assets\OneSignal\Platforms\iOS\Info.plist".

Like, looking it totally different place. Is that just me?

**Comment by Nightsd01** [comment]
Assuming that you managed to fix the issue since you did not respond, closing the issue. If you're still having this problem please feel free to respond and we'll be happy to reopen and help investigate.

**Comment by RyuMaster** [comment]
Hi! Sorry for being away. I am creating my build on Windows, it appears in there. Started to happen just recently, I used OneSignal building on Windows before without any issues.

**Comment by Nightsd01** [comment]
@RyuMaster How are you building iOS in Windows?

**Comment by RyuMaster** [comment]
I am exporting xCode project and building it on iOS. That is a typical stuff for Windows-users. This error happens during the export phase, nearly the very end.

**Comment by Nightsd01** [comment]
@RyuMaster Is that an exact copy and paste of the error, or did you add the X's? If so, can you post the full error?

**Comment by DmitriyYukhanov** [comment]
I have same error while making iOS build to XCode from Unity while doing this on Mac:

DirectoryNotFoundException: Could not find a part of the path "/Users/admin/Desktop/Rostelecom/Assets/OneSignal/Platforms/iOS/Info.plist".

That's because I moved OneSignal folder to the 
/Users/admin/Desktop/Rostelecom/Assets/ThirdParty/OneSignal/

This is a common issue with many Unity Assets developers - they hardcode paths and force customers to bloat Assets root folder which is a very bad practice.

Please consider auto-detecting OneSignal folder location in future updates of the SDK.

**Comment by DmitriyYukhanov** [comment]
@RyuMaster you'll have to put OneSignal folder to the Assets root to workaround this issue until it gets fixed.

**Comment by Nightsd01** [comment]
@DmitriyYukhanov Our SDK includes a buildscript for iOS purely for your convenience - you can disable it if you want. I am not actually aware of a way that our build script _could_ autodetect its path if it's not at the root of the `Assets` folder - are you?
