### ISSUE TITLE
2.9.0 duplicate _cStringCopy symbol linker error

### ISSUE THREAD

**Issue by imtrobin** [OneSignal/OneSignal-Unity-SDK#227]
Hi, I'm unable to build on IOS as it complains of duplicate symbol _cStringCopy also in GameAnalaytics sdk, and onesignal 2.9.0 during linking

**Comment by VGMFR** [comment]
Same issue here. Was hopping to fix [this](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/217) by updating, and I am now unable to compile on iOS :')

**Comment by muzhikant** [comment]
Same here. Wanted to fix one bug (not critical) - got another one, critical.
Any devs here?  Any estimates?

**Comment by jkasten2** [comment]
We will have an official release next week to fix this issue. Thanks.

**Comment by coolabingge** [comment]
the same issue here.  i had back the version to 2.8.2

**Comment by muzhikant** [comment]
Guys! It have been much more than week! Please, release update

**Comment by PhilippeLbcStudios** [comment]
We are currently on Unity 2017.4.33f1. I was able to compile by downgrading. Unity to 2017.4.32f1.
Because 33f1 and 32f1 are so similar and doesn't change the save file of one's project, you can try to downgrade just by changing the version number of your project in ProjectSettings/ProjectVersion.txt to 2017.4.32f1 (with your project closed) and open it with the 2107.4.32f1.

**Comment by jkasten2** [comment]
We just released [OneSignal-Unity-SDK 2.9.1](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.9.1) to fix this `_cStringCopy` link error.
