### ISSUE TITLE
The imported type `Google.JarResolver.Dependency' is defined multiple times

### ISSUE THREAD

**Issue by ipulcrimx** [OneSignal/OneSignal-Unity-SDK#24]
Hi, I just imported one signal to my unity project then I find these errors. I said that PlayServiceSupport has duplicate in JavaResolverLib (the one from admob). I tried to delete one of them and the result is I can't build my apk when I deleted GoogleJarResolver and the unity crashed when I deleted the other one. Can someone help me with this?

Thanks

**Comment by darwin2k** [comment]
same for me :/

**Comment by jkasten2** [comment]
@ipulcrimx @darwin2k You can delete the `PlayServicesReslover` in the `Assets` folder and re-import the OneSignal plugin to correct this issue.

The root of the issue is due to our naming of the `DLL` files in folder conflicting with other plugins when added. We will be fixing this by updating to the latest JarResolver library and naming the files correctly. After our update you may still need to restart Unity so it can remove the old DLLs when importing the plugin.

Thanks.

**Comment by sunderplugs11** [comment]
Was this not fixed? I cant use the OneSignal versions it seems.

**Comment by jkasten2** [comment]
@sunderplugs11 In our latest 2.1.4 SDK we corrected the `dll` names to include the version number as Google has noted so this is correct compatibility with other plugins using them. If your coming from an older version for the OneSignal SDK you will most likely still have to delete the `PlayServicesReslover` folder manually and reimport to correct the issue however.

Let us know if you continue to see an issue.

**Comment by jkasten2** [comment]
@ipulcrimx @darwin2k @sunderplugs11 We just updated to the Google jar resolver 1.2.16.0 in our 2.2.1 release. Feel free to reopen this issue if you run into the same problem after updating.
