### ISSUE TITLE
OneSignal tracking not working with Unity Mobile Notifications 

### ISSUE THREAD

**Issue by czanier** [OneSignal/OneSignal-Unity-SDK#245]
**Description:**

OneSignal open app tracking stops working when Unity's project also includes Unity Mobile Notifications package

**Environment**

* iOS 13.1.3
* Unity 2018.4.11f
* Unity OneSignal SDK v2.10.0
* Unity Mobile Notifications Package v1.0.3 
(https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0/manual/index.html)

**Steps to Reproduce Issue:**

1. Import OneSignal SDK v2.10.0
1. Import Unity Mobile Notifications v1.0.3 from Unity's Package Manager
1. Send a Notification using OneSignal's dashboard
1. Open app from that notification

**Comment by jkasten2** [comment]
The sounds like an issue where Unity Mobile Notifications Package is causing an iOS Swizzling issue where the OneSignal SDK is not getting the notification open event. It seems there has only been one report of this issue, can you try the latest Unity Mobile Notifications Package v1.3.2 to see if this is still an issue for you?

**Comment by tanaynigam** [comment]
The issue has been fixed in our recent release. You can download the OneSignal-Unity-SDK [release 2.13.5](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.13.5) from our OneSignal-Unity-SDK release page or directly from the [Unity Asset Store](https://assetstore.unity.com/packages/add-ons/services/billing/onesignal-sdk-193316).

We tested the the One-Signal-Unity-SDK alongside Unity Mobile Notification Package.`OneSignal.HandleNotificationOpened` now handles OneSignal notifications correctly. The `iOSNotificationCenter.GetLastRespondedNotification` handler will correctly read Unity and OneSignal notifications. The `Unity.iOS.NotificationServices.remoteNotifications[0]` will also retrieve Unity and OneSignal notifications. The `Unity.iOS.NotificationServices.remoteNotifications[0]` is, however, a deprecated in 2018+ Unity versions.

#### The environment used for these tests
* Unity 2020.3.6f1
* OneSignal-Unity-SDK 2.13.5
* Unity Mobile Notifications 1.3.2
* iOS 14.5.1

#### Note
If `iOSNotificationCenter.OnRemoteNotificationReceived` has been setup on the app, `OneSignal.inFocusDisplayType` will not work causing the OneSignal notification to not display on the device when the app is on the foreground, unless you display local notification using Unity Mobile Notifications
