### ISSUE TITLE
Subscribed status is "Apns Delegate Never Fired" in the panel 

### ISSUE THREAD

**Issue by RealMSHB** [OneSignal/OneSignal-Unity-SDK#277]
I implemented the new version of Onesignal and there is no error when I build on the device. I'm also using "OneSignal.kOSSettingsAutoPrompt, false".
when the prompt for enabling the notification is shown then the user presses Allow the Init gets called and it shows the user id but the subscription is always false even though I set it to true and in the one signal panel, all the users that have iOS devices have "Apns Delegate Never Fired" in the subscription status.
The problem only occurs on iOS.

Unity 2019.3.1
One Signal 2.11.4

here is the PodFile in case you need it:
```
target 'Unity-iPhone' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.53'
end
target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.53'
end
```

**Comment by jkasten2** [comment]
@RealMSHB The Apns Delegate Never Fired" error could be from one of the following:
1. Another SDK or library in your Unity project that is incorrectly swizzling the AppDelegate in native code.
   - If this issue is from another library please reproduce the issue in a new project and provide the exact library and version giving you the issue.
   - The other library may not be in your Podfile.
2. It could be a network issue connecting to Apple's APNs server. Please test on multiple iOS devices or try toggle your WiFi. This might only be an issue with Sandbox builds of your app.
   - https://github.com/OneSignal/OneSignal-iOS-SDK/issues/514

**Comment by rgomezp** [comment]
Closing due to no response
