### ISSUE TITLE
Does this product work? It has never built for me, i been trying for months.

### ISSUE THREAD

**Issue by nsmith1024** [OneSignal/OneSignal-Unity-SDK#311]
Create a new project, import OneSignal package, set build target to android

force resolve

One signal pops up message box "resolution failed! your application will not run"

**Description:**
OneSignal is the only thing in the project and it still doesnt work

**Environment**

Unity version 2020.1

**Steps to Reproduce Issue:**
Create new  project, import OneSignal, set build target to android
cant build

**Comment by rgomezp** [comment]
Howdy,
Yes, OneSignal works. It sounds like you may need some set-up help. 

I would encourage you to visit OneSignal.com and reach out to our support team who would be happy to assist.

Cheers

**Comment by jkasten2** [comment]
@nsmith1024 We have tested with the latest 2020.1.0f1 release of Unity OneSignal is working correctly.

Since you are seeing the "resolution failed! your application will not run" error on a fresh new project then this is most likely an issue with a connection to Google. Please check the error details on which calls failed.
