### ISSUE TITLE
Registering for push notifications on iOS blocked by Jumbo Privacy "Block Trackers" feature

### ISSUE THREAD

**Issue by justin-pierce** [OneSignal/OneSignal-Unity-SDK#322]
Not sure it matters but iOS 13.3, Unity 2018.4.13, Unity SDK 2.13.1

Error: 
`ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=0 "(null)" UserInfo={error=Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x2834051a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=https://api.onesignal.com/players, NSErrorFailingURLKey=https://api.onesignal.com/players, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}}`

Disabling the "Block Trackers" feature in [Jumbo Privacy](https://www.jumboprivacy.com/) fixed it. After registering with it turned off, it seems I can receive push notifications with it turned back on.

**Comment by rgomezp** [comment]
Howdy,
Thank you for reporting this issue. Unfortunately there isn't anything we can immediately do since Jumbo uses the device's VPN API to block outgoing requests to a blocked list of URLs at the device level.

In any case, we will explore our options to see if we can get removed from their trackers list in the future. Thanks again.
