### ISSUE TITLE
UserId callback with timeout

### ISSUE THREAD

**Issue by FurionTheGreatest** [OneSignal/OneSignal-Unity-SDK#360]
**Description:**
#featurerequest

Can you, please, add callback for user id received from GetPermissionSubscriptionState() with timeOut.
Because even if I init correctly I can't retrieve it.

If I use IdsAvailable() and something goes wrong (no OneSignal id assigned, any other troubles) it causes endless loading

**Comment by jkasten2** [comment]
@FurionTheGreatest Thanks for reporting.

In the 3.0.0 release `GetPermissionSubscriptionState` has been changed to `OneSignal.Default.PushSubscriptionState`.

```C#
var pushState        = OneSignal.Default.PushSubscriptionState;
var pushUserId       = pushState.userId;
var pushIsSubscribed = pushState.isSubscribed;
```
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md#push-notifications


To upgrade from 2.x.x to 3.x.x please follow the full migration guide:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md#onesignal-unity-sdk-2xx-to-3xx-migration-guide

> Can you, please, add callback for user id received from GetPermissionSubscriptionState() with timeOut.
Because even if I init correctly I can't retrieve it.

Let us know if the above new API still has the timeout issue you noted. Please provide you code if this is still an issue.

**Comment by binouze** [comment]
Hi,
there is a problem with this new way of getting userId.

If I try to retrieve OneSignal.Default.PushSubscriptionState.userId right after OneSignal Initialisation, I got OneSignal.Default.PushSubscriptionState null. 

If I wait a little more OneSignal.Default.PushSubscriptionState is not null anymore but the userId is still empty.

So to get the same behaviour as the old IdsAvailable() I had to wrap it in an async method.

`public async void IdsAvailable( Action<string> IDAvailable )
{
    while( string.IsNullOrEmpty(OneSignal.Default?.PushSubscriptionState?.userId ?? "") )
        await Task.Yield();
    
    IDAvailable?.Invoke( OneSignal.Default.PushSubscriptionState.userId );
}`

**Comment by jkasten2** [comment]
@binouze I recommend checking if `OneSignal.Default?.PushSubscriptionState?.userId` is not `null`, use the value if it is. If it is `null` you can use the `PushSubscriptionStateChanged` to get the value as soon as it becomes available. 

```C#
OneSignal.Default.PushSubscriptionStateChanged += (current, previous) => {
    var userId   = current. userId;
};
```
