### ISSUE TITLE
Custom notifications icons never replace the standard OneSignal building .apk/aab

### ISSUE THREAD

**Issue by novavision** [OneSignal/OneSignal-Unity-SDK#398]
**Description:**
Replacing icons in Plugins/Android/OneSignalConfig/res/drawableXXXX never being updated creating new .apk/.aab even cleaning up the cache.

**Environment**
Any OneSignal

**Steps to Reproduce Issue:**
1. integrate OneSignal in Unity project
2. create a build
3. send OneSignal message - OneSignal default icons will be shown
4. replace ic_stat_onesignal_default in Plugins/Android/OneSignalConfig/res/drawableXXXX
5. add 
` <meta-data android:name="com.onesignal.messaging.default_notification_icon"
        android:resource="@drawable/ic_stat_onesignal_default" /> <meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="FFFFFF" />`
        to AndroidManifest.xml
5. create a new build
6. send OneSignal message - same old OneSignal icons will be shown. It never will update

**Anything else:**
As Unity experts says, it's not recommended just replace the icons images in that folder, but need to create .aar library for that. I have no clue how to do it. Would be great if you update documentation to make the things work as expected.
Please provide the solution here as well.

**Comment by jkasten2** [comment]
@novavision Thanks for reporting, I am not sure which OneSignal SDK version you are on but the folder should be `OneSignalConfig.plugin` instead of `OneSignalConfig` which might be the issue. See the [full OneSignal Icon documentation](https://documentation.onesignal.com/docs/customize-notification-icons) for more details.

I recommend updating to the new OneSignal-SDK-Major version 3, it is required to target android API level 31.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/3.0.1

> As Unity experts says, it's not recommended just replace the icons images in that folder, but need to create .aar library for that. 

Unity is right that is is an option, but more complex than needed for just icons. Placing the icons in the `OneSignalConfig.plugin` and the OneSignal SDK will take care of it.
