### ISSUE TITLE
Automatically add Push Capabilities to support iOS Unity Cloud builds

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Unity-SDK#40]
This improvement will also make local builds simpler.

Will also need to add the `UserNotifications.framework` dependency.

**Comment by Gwom** [comment]
This may help: https://forum.unity3d.com/threads/how-to-put-ios-entitlements-file-in-a-unity-project.442277/

Though not sure how to add the target, it may help with the entitlements - all in all though, if you include something like this in the setup package, the steps for unity integration on iOS may be reduced.

**Comment by Arodus** [comment]
There is an updated version of the xCode Api available at: https://bitbucket.org/Unity-Technologies/xcodeapi . Maybe the updated version is already bundled with newer versions of unity but im not sure about that.

The new version contains ProjectCapabilityManager which gives you the ability to easily modify the capabilities:

 `   private static void OneSignalPostBuild(BuildTarget target, string buildPath)
        {
            var capManager = new ProjectCapabilityManager(buildPath, "com.example");
            capManager.AddPushNotifications(Debug.isDebugBuild);
                
           
            var project =  capManager.PBXProject;
            var targetGuid = project.TargetGuidByName(PBXProject.GetUnityTargetName());
            project.AddFrameworkToProject(targetGuid,"UserNotifications.framework",false);
            
           capManager.Close();
        }`

Adding the framework is already possible since Unity 5.x.

**Comment by lulzbane** [comment]
We have version 2.1.4 of the unity plugin installed and it works fine with cloud build, but the actual push notifications from that version only work for ios 9 and below, when upgrading to 2.3.3 the ios cloud builds stopped working and so I've reverted to 2.1.4 for now but we do want to get ios 10 push notifications working so looking forward to this fix. Just thought I would mention this because it was clearly something post 2.1.4 that broke the cloud build :)

**Comment by sharklab** [comment]
any news about this?

**Comment by jkasten2** [comment]
`CLANG_ENABLE_MODULES` may also be needed to support cloud building.
https://github.com/scarlet/ScarletPostProcessor/blob/master/ScarletPostProcessor.cs

**Comment by Nightsd01** [comment]
Fixed in #85

**Comment by studentutu** [comment]
@arodus also, with new Unity 2018: ProjectCapabilityManager no longer has close() method (use capManager.WriteToFile();). It would be helpful if someone could make a tutorial on how to add Entitlements with XcodeApi...
