### ISSUE TITLE
[Bug]: TargetGuidByName("OneSignalNotificationServiceExtension") returns null (ios)

### ISSUE THREAD

**Issue by asiepshtain** [OneSignal/OneSignal-Unity-SDK#509]
### What happened?

Upgraded to OneSignal 3 from 2.6.

Project contains a OnPostprocessBuild  for ios in order to dynamically assign the correct provisioning profile and certifacte.
However TargetGuidByName("OneSignalNotificationServiceExtension") returns null.

Oddly, even thou TargetGuidByName returns null, opening the workspace shows 'OneSignalNotificationServiceExtension' as target and after manually assigning the certificate the build works.

This worked fine until the upgrade.

### Steps to reproduce?

```Markdown
1. install one signal 3
2. create a post process ios build class
3. get a refrence to PBXProject and attempt getting oneSignalExtGuid 
[   
public static void OnPostprocessBuild(BuildTarget target, string path) {
PBXProject proj = new PBXProject ();
proj.ReadFromString (File.ReadAllText (projPath));
string oneSignalExtGuid = proj.TargetGuidByName("OneSignalNotificationServiceExtension");
}
]
4. build for ios
```

### What did you expect to happen?

oneSignalExtGuid should contain oneSignalExtGuid

### Unity version

2019.4.30

### OneSignal Unity SDK version

3.0.1

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asiepshtain** [comment]
Tried upgrading to 3.0.2 as it's patch notes seemed very releveant:

* iOS build post processor checks for complete presence of extension

However the behaviour remains the same

**Comment by adamschlesinger** [comment]
Hi @asiepshtain if your exported project contains the `OneSignalNotificationServiceExtension` it seems likely that the SDK's `OnPostprocessBuild` is occurring after the one you have setup. The OneSignal Unity SDK has the `callbackOrder` set as `45` in order to fall within the range set by EDM4U outlined [here](https://github.com/googlesamples/unity-jar-resolver#appending-text-to-generated-podfile). If you are modifying the `OneSignalNotificationServiceExtension` after it is generated ensure that your class implementing `IPostprocessBuildWithReport` has a `callbackOrder` of `46` or higher.

**Comment by asiepshtain** [comment]
setting callbackOrder to 46 worked like a charm.
Thanks!
