### ISSUE TITLE
How to send silent push between user?

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#59]
I use onesignal unity SDK to implement user messaging in my game. I want user able to send message between each other just when they are both active so I think I would use silent push

But it seem onesignal unity SDK cannot send silent push. When one user close the app it send notification to another user. I don't want that so how to avoid it?

**Comment by jkasten2** [comment]
Normally push notifications are used to notify the user when they are outside your app. Instead of trying to suppress the visual notification I recommend sending one only when you think the user is available. Do you track when the user is online in your game? Or the last time they opened the app?

You can use the `last_session` field on `filters` to target the user if say they opened your app in the last day. You will also need to add a tag filter entry to target a specific user or a list of them.
https://documentation.onesignal.com/v3.0/reference#section-send-to-users-based-on-filters

You can however only user filters from your server, not from within your app for security. I also recommend setting a low `ttl` of a few minutes so the user's device is offline they won't get it later when going back online when it is no longer relevant.

**Comment by Thaina** [comment]
I try to used your suggestion but still got some issue in #60 but this issue considered solved. Thanks
