### ISSUE TITLE
[Bug]: Shows permission prompt without calling RequestPermissionAsync

### ISSUE THREAD

**Issue by AFB-MORA** [OneSignal/OneSignal-Unity-SDK#637]
### What happened?

SDK automatically shows iOS permission prompt without calling OneSignal.Notifications.RequestPermissionAsync(true)

### Steps to reproduce?

```Markdown
1. Install OneSignal 5.0.2
2. Initialize OneSignal with app id
3. Build project for iOS
4. Run the app
```

### What did you expect to happen?

The prompt should **NOT** be shown.

### Unity version

2022.3.2f1

### OneSignal Unity SDK version

5.0.2

### Platform

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Could you share the following details, I was unable to reproduce the issue

Do you have any other SDKs installed?
What devices are you seeing this issue on and what version of iOS are they using?
Could you reproduce this issue in a new project and share it with us?

**Comment by AFB-MORA** [comment]
I found the problem. I was calling ```OneSignal.User.PushSubscription.OptIn();``` before calling ```OneSignal.Notifications.RequestPermissionAsync(true)```. I think "OptIn" shows permission prompt, if called first. I don't know this is a bug or by design.

**Comment by shepherd-l** [comment]
Yes this is by design

`OptIn()` will display the permission prompt if the users hasn’t been prompted. If the user has already been prompted and the app’s settings notifications permission is disabled, the user will see a prompt to direct them to the settings app.

We created `OptIn()` as a shorthand method for developers to use. `OneSignal.Notifications.requestPermissionAsync()` can be used for more control.

Let me know if you have any questions

And thanks for the feedback, I plan on updating the migration guide to make this more clear.
