### ISSUE TITLE
[question]: How to push notification by code for a specific user

### ISSUE THREAD

**Issue by ChakibBenssoum** [OneSignal/OneSignal-Unity-SDK#672]
### How can we help?

Hello ! 
I try to set-up a auto-notification system for my users, and i checked the example provided.
Sadly, the version isn't the right one (3.0.11, mine is 5.0.5).
I checked the migration guide, i tried to find the method "PostNotification" in the new api, but i really don't find how to do it. Can i have some help please ? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Hello!
PostNotification was removed in 5.x

We recommend using our API to send notifications rather than sending them on the device level due to the potential security issue of exposing another user's id on the device.

You can find our API documentation here: https://documentation.onesignal.com/reference/create-notification

If this doesn’t work for your use case, could you explain what your use case is?

**Comment by ChakibBenssoum** [comment]
Thanks for your help, i finally find a solution.
Have a nice day !
