### ISSUE TITLE
[question]: How to fix com.android.build.gradle.internal.tasks.Workers$ActionFacade

### ISSUE THREAD

**Issue by blprncc** [OneSignal/OneSignal-Unity-SDK#687]
### How can we help?

com.android.build.gradle.internal.tasks.Workers$ActionFacade

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Could you please provide the entire error message? What version of the OneSignal Unity SDK are you using? And what version of the Unity Editor are you using?

**Comment by jkasten2** [comment]
Is `com.android.build.gradle.internal.tasks.Workers$ActionFacade` a runtime error or a build error? Can you provide the fullstack trace or build error log around it?

Closing due to no response, please provide the all the required details on our bug ticket report:
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yml&title=%5BBug%5D%3A+
