### ISSUE TITLE
Can't build after import to my project. Dex classes limit

### ISSUE THREAD

**Issue by 3d03** [OneSignal/OneSignal-Unity-SDK#71]
Can you publish "Lite" version of SDK with basic functionality?
Now i can't build Android APK due to DEX classes limitation.  Or Maybe you can publish project example with Gradle build system?

**Comment by jkasten2** [comment]
@3d03 The OneSignal SDK itself is less than 2k methods out of the 64k limit. Most of the method counts hitting the dex limit are due to the Android Support Library and the Google Play services library OneSignal depends on. Most of the methods in these 2 libraries are not used by OneSignal so they can be optimized out with Proguard to solve your DEX limit issue.

Unity now has Gradle as a "Build System" option so you don't need to export the project to take advantage of Proguard. See Unity's docs on enabling this.
https://docs.unity3d.com/Manual/android-gradle-overview.html 
The current OneSignal Unity version 2.6.3 requires a small work around noted below but will no longer with the next update:
https://github.com/OneSignal/OneSignal-Unity-SDK/issues/86#issuecomment-373873847
