### ISSUE TITLE
[question]: No response on PromptForPush()

### ISSUE THREAD

**Issue by G-r-i-n-c-h** [OneSignal/OneSignal-Unity-SDK#710]
### How can we help?

Just Checking if the behavior is correct.
Using new 5.1.1 version of the SDK and Example app from git.
On android 12 and bellow calling PromptForPush() does not give callback at all.
the last line on console is 
"Opening permission prompt for push notifications and awaiting result..."
However on android 13+ it pops up default notification view and all works as expected.
Does anyone have the same problem ? (its clean example project nothing has been changed)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Good question!

OneSignal.Notifications.RequestPermissionAsync() does not return if notification permission is already granted, this is true for both Android 12 and 13.

Android 13+ requires prompting users for permission but on Android 12, permission is automatically granted by default and users are expected to opt out instead.

Because Android 12 grants permission by default, notification permission is already given and calling OneSignal.Notifications.RequestPermissionAsync() does not return, causing the behaviour you see.

You can read more about [Prompt for push notification permissions](https://documentation.onesignal.com/docs/mobile-sdk#prompt-for-push-notification-permissions) on our docs.

Let me know if you have any questions!

**Comment by shepherd-l** [comment]
@snoova 

I recommend checking that `OneSignal.Notifications.Permission` is false inorder to call `await OneSignal.Notifications.RequestPermissionAsync();`

**Comment by shepherd-l** [comment]
This should be fixed in the latest [5.1.7 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/5.1.7). Please create a new issue if this is still a problem
