### ISSUE TITLE
Apple Mach-O linker id error

### ISSUE THREAD

**Issue by lukson666** [OneSignal/OneSignal-Unity-SDK#72]
Hello,

I am trying to use OneSignal SDK with Unity version 2017.2 and newest Xcode 9. After I export my project from Unity to Xcode and trying to build it to iPhone, I get the following 3 errors:
<img width="855" alt="screen shot 2017-10-23 at 18 32 32" src="https://user-images.githubusercontent.com/33034712/31901260-366f9e94-b821-11e7-9a09-dfc4e0c23cd3.png">
Any ideas ? 

Regards, L

**Comment by advantage-software** [comment]
I'm seeing the same issue

**Comment by jkasten2** [comment]
@lukson666 @advantage-software You need to add the `UserNotifications.framework` to the Xcode project. See steps 5.5. through 5.7 below.
https://documentation.onesignal.com/docs/unity-sdk-setup#section-5-ios-setup-part-1

**Comment by jkasten2** [comment]
Feel free to reopen if the above did not solve your issue.

**Comment by lulzbane** [comment]
hello, is there any way of troubleshooting this without xcode? we are getting a similar error on the unity cloud builds but it hasn't been a problem for us before, only recently.

this is what i get in the logs...
`9191: ▸ Compiling OneSignalUnityRuntime.m
9192: ⚠;️  /BUILD_PATH/ap-point.projecttracker-qa.qa-ios-enterprise/temp.XXXXXX20180117-2970-rybk8m/Libraries/OneSignal/Platforms/iOS/OneSignalUnityRuntime.m:178:16: 'registerForPushNotifications' is deprecated: Please use promptForPushNotificationsWithUserResponse instead. [-Wdeprecated-declarations]
9193: [OneSignal registerForPushNotifications];
9194: ^
9195: ▸ Linking opusqa
9196: ▸ Linking opusqa
9197: ❌;  ld: symbol(s) not found for architecture arm64
9198: ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
9199: ** ARCHIVE FAILED **
9200: The following build commands failed:
9201: Ld /BUILD_PATH/Library/Developer/Xcode/DerivedData/Unity-iPhone-cinpuiwkdvljvthkzxykqcbctfgy/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/opusqa normal arm64
9202: (1 failure)
9203: Exit status: 65
9204: Maybe the error shown is caused by using the wrong version of Xcode
9205: Found multiple versions of Xcode in '/APPLICATION_PATH/'
9206: Make sure you selected the right version for your project
9207: This build process was executed using '/APPLICATION_PATH/Xcode9_0_0.app'
9208: If you want to update your Xcode path, either
9209: - Specify the Xcode version in your Fastfile
9210: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
9211: - Specify an absolute path to your Xcode installation in your Fastfile
9212: ▸ xcode_select "/APPLICATION_PATH/Xcode8.app"
9213: - Manually update the path using
9214: ▸ sudo xcode-select -s /APPLICATION_PATH/Xcode.app
9215: +-------------+------------------------------+
9216: |             Build environment              |
9217: +-------------+------------------------------+
9218: | xcode_path  | /APPLICATION_PATH/Xcode9_0_0.app |
9219: | gym_version | 2.62.1                       |
9220: | sdk         | iPhoneOS11.0.sdk             |
9221: +-------------+------------------------------+
9222: ▸       objc-class-ref in libOneSignal.a(OneSignalHelper.o)
9223: ▸       objc-class-ref in libOneSignal.a(OneSignalNotificationSettingsIOS10.o)
9224: ▸       objc-class-ref in libOneSignal.a(UNUserNotificationCenter+OneSignal.o)
9225: ▸ ld: symbol(s) not found for architecture arm64
9226: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
9227: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
9228: 📋  For the complete and more detailed error log, check the full log at:
9229: 📋  /BUILD_PATH/Library/Logs/gym/opusqa-Unity-iPhone.log
9230: Looks like fastlane ran into a build/archive error with your project
9231: It's hard to tell what's causing the error, so we wrote some guides on how
9232: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
9233: Before submitting an issue on GitHub, please follow the guide above and make
9234: sure your project is set up correctly.
9235: fastlane uses `xcodebuild` commands to generate your binary, you can see the
9236: the full commands printed out in yellow in the above log.
9237: Make sure to inspect the output above, as usually you'll find more error information there
9238: +------------------+-------+
9239: |       Lane Context       |
9240: +------------------+-------+
9241: | DEFAULT_PLATFORM | ios   |
9242: | PLATFORM_NAME    |       |
9243: | LANE_NAME        | build |
9244: +------------------+-------+
9245: Error building the application - see the log above`

**Comment by jkasten2** [comment]
@lulzbane Unity Cloud build support was added in our 2.6.1 SDK
https://github.com/OneSignal/OneSignal-Unity-SDK/releases

**Comment by lulzbane** [comment]
thanks @jkasten2  we were on 2.5.0
