### ISSUE TITLE
When I killed app, can I recieve the notification?

### ISSUE THREAD

**Issue by tonywya** [OneSignal/OneSignal-Unity-SDK#74]
Hi,

Is there any way to receive notification when the application is force killed?

Thanks.

**Comment by jkasten2** [comment]
@tonywya The following troubleshooting guide covers all the cases where a notification may not show.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

Please provide more details about about which platforms, versions, and logs if the above does not solve your issue.

Thanks.

**Comment by tonywya** [comment]
Hi,

My test device is Huawei Honor6, Emui3.1, Android5.1.1.
When I kill the app, then send the notification, the adb log is like this:

W/GCM-DMM ( 6345): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.myPackageName.google (has extras) } 

It seems that the service is shutted down, is there any way to restart the service again?

Thanks.

**Comment by jkasten2** [comment]
@tonywya Since the device force killed your app most intents such as a push won't be able to start your app again until the user opens your app again. On most Android devices swiping a way the app does not put it in to a force closed / force killed state. However Huawei devices before EMUI4.1 are one of the devices know to do this.

See this OneSignal's blog post on a list of devices that do this and what settings can be changed to prevent this issue.
https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/

**Comment by tonywya** [comment]
thanks @jkasten2 , but i mean manually kill the app not automatically killing background apps

**Comment by piotrkst** [comment]
@tonywya I guess it won't be possible using this SDK

**Comment by Grayson-mysqli** [comment]
> [@tonywya](https://github.com/tonywya) Since the device force killed your app most intents such as a push won't be able to start your app again until the user opens your app again. On most Android devices swiping a way the app does not put it in to a force closed / force killed state. However Huawei devices before EMUI4.1 are one of the devices know to do this.
> 
> See this OneSignal's blog post on a list of devices that do this and what settings can be changed to prevent this issue. https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/





https://lnkr.fun/be4ff4d
