### ISSUE TITLE
Unable to merge android manifests. 

### ISSUE THREAD

**Issue by Slogunn** [OneSignal/OneSignal-Unity-SDK#76]
Showing error as Unable to merge android manifests. 
```java
OneSignalExample\Temp\StagingArea\android-libraries\runtime-1.0.3\AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='25'> but library uses targetSdkVersion='26'
]
```

Please fix the issue or is there any solution to fix this issue

**Comment by jkasten2** [comment]
@Slogunn Can you sure your `config.xml` and list all your plugins with `cordova plugin list` so we can look into producing this error?

**Comment by jkasten2** [comment]
@Slogunn Can you set your Android target SDK version in the Android Build settings to API level 26?

**Comment by tonisuo** [comment]
I got this same error and after updating my android SDK and build tools still didnt work. The problem was that somehow the androidSDK folder that had the old sdks didnt receive the updates through Android Studio so I had to change the folder in unitys External Tools-->Android SDK to the the Android Studios installation folder. Then Unity recognized the new 26 version of the sdk.
