### ISSUE TITLE
Caused by android.os.DeadSystemException

### ISSUE THREAD

**Issue by jgersindemir** [OneSignal/OneSignal-Unity-SDK#95]
We are developed game using Unity One Signal SDK. I got crash from SDK 
Onesignal Unity SDK version : 2.6.3
Unity version : 5.6.5
App In Background : Yes
Android OS : 7 
Device : HUAWEI

```java
Caused by android.os.DeadSystemException
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:162)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:145)
       at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1120)
       at com.onesignal.OneSignal.access$2200(OneSignal.java:81)
       at com.onesignal.OneSignal$7.run(OneSignal.java:1091)
       at java.lang.Thread.run(Thread.java:776)
```

**Comment by Nightsd01** [comment]
@jgersindemir Can you please add more details? When does this issue occur? Can you easily reproduce it?

**Comment by jgersindemir** [comment]
It is hard to reproduce it. We saw that error on Fabric. If we find  more details , let me known.

**Comment by Nightsd01** [comment]
@jkasten2 Any idea what could be causing this? 

It looks like this line (getting `game_version` parameter) could be responsible:

```java
try {
         deviceInfo.put("game_version", packageManager.getPackageInfo(packageName, 0).versionCode);
      } catch (PackageManager.NameNotFoundException e) {}
```

**Comment by jkasten2** [comment]
@jgersindemir This is due to the the Android core system process dying and then restarting on the device. There isn't really much that can be done in your app, it is due to a bug in the system ROM on the device. A number of API will throw when the app is in this state, it just happened to be OneSignal in this case. More details it the thread below

https://stackoverflow.com/a/44395215/1244574

Thanks

**Comment by mtrezza** [comment]
@jkasten2 That may be the theoretical answer. However, there are documented cases where the crash can be caused by the app. The `android.os.DeadSystemException` just makes it seem that the reason is external.

Cases:
- https://proandroiddev.com/oreo-notification-feature-a-critical-issue-that-could-restart-your-android-phone-ca122fa4d9cb
- https://stackoverflow.com/questions/56406974/what-causes-deadsystemexception-with-android-gms-dynamite-mapsdynamite

**Comment by rgomezp** [comment]
There are reports of the crash being caused by a bug in the notification service of Android version 7 and 8.
